// Generated by CoffeeScript 1.6.2
(function() {
  var $cover, $fire, $water, bottom, currBottom, currTop, dir1, dir2, h, step1, stepCount, top, vector1, vector2, waterHeight, waterY,
    _this = this;

  h = {
    getRand: function(min, max) {
      return Math.floor((Math.random() * ((max + 1) - min)) + min);
    }
  };

  $fire = $('#fire-path');

  $cover = $('#cover');

  $water = $('#water');

  waterHeight = parseInt($water.attr('height'), 10) + .75;

  waterY = parseInt($water.attr('y'), 10);

  console.log(waterHeight, waterY);

  setInterval(function() {
    waterHeight = waterHeight - 1;
    waterY = waterY + 1;
    $water.attr('y', waterY);
    return $water.attr('height', waterHeight);
  }, 100);

  top = 30.808;

  bottom = 27.988;

  vector1 = top - bottom;

  vector2 = bottom - top;

  stepCount = 20;

  step1 = vector1 / stepCount;

  dir1 = false;

  dir2 = false;

  currTop = bottom;

  currBottom = top;

  setInterval(function() {
    if (!dir1) {
      if (currTop <= top) {
        currTop += step1;
      } else {
        dir1 = true;
      }
    } else {
      if (currTop >= bottom) {
        currTop -= step1;
      } else {
        dir1 = false;
      }
    }
    if (!dir2) {
      if (currBottom >= bottom) {
        currBottom -= step1;
      } else {
        dir2 = true;
      }
    } else {
      if (currBottom <= top) {
        currBottom += step1;
      } else {
        dir2 = false;
      }
    }
    return $fire.attr('points', "23," + (top - 1) + " \n21.804," + currTop + "\n18.985," + currBottom + "\n16.134," + currTop + "\n13.284," + currBottom + "\n10.404," + currTop + "\n9," + (top - 1) + "\n");
  }, 5);

  setInterval(function() {
    return $cover.attr('transform', "rotate(" + (h.getRand(-4, 4)) + ",16,2)");
  }, 20);

}).call(this);
